# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c275945297b8a69fdc4f94d0767de94ee9e3d094491c46b308d65755fd4535e4699af3e3095548d1dc356fa26ad76705dc4cf33781db834d8a3ef47cec30c49

test:
  secret_key_base: aad254cbbcbb001a89fae40c8ebb71dbe662aa5d8a5b3a56528642ecfad7db5047d2f73902359409a5a3132ead6cd9167c740086e9f9e91901e1ad62a6b3c4a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
